### ISSUE TITLE
Modal not working properly!

### ISSUE THREAD

**Issue by biholaindrasinh** [enso-ui/modal#6]
This is a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description
I have installed enso-ui/modal using **yarn add @enso-ui/modal**
When I run it I can see the model but I am not able to close it. I am using one boolean variable to show/hide modal.

### Steps to Reproduce
1. First Step
Install package.
2. Second Step
`import { ModalCard } from '@enso-ui/modal/bulma';`
3. Third Step
put it inside component's template like this:
`<modalCard :show="isActive" @close="close"/>`

### Expected behavior
Modal should be visible when **isActive** value is true and hide when **isActive** value is false when clicking on the close button.

### Actual behavior
Modal is visible even **isActive** true/false. I am not able to close it even after setting **isActive** value to false in close method.

**Comment by aocneanu** [comment]
Hi @biholaindrasinh 

There is no need for "show" anymore. Instead you should use `v-if="isActive"`

**Comment by aocneanu** [comment]
@gandesc please update docs
